# Generated by Django 3.2.5 on 2021-07-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ref_slug',
            field=models.URLField(unique=True),
        ),
    ]
